version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=zebra
      - DB_PASSWORD=zebra
      - DB_NAME=zebrabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: zebra
      POSTGRES_PASSWORD: zebra
      POSTGRES_DB: zebrabase
    ports:
      # - "5432:5432"
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
